name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on EC2 Self-Hosted Runner
    runs-on: self-hosted  # Runs directly on your EC2 instance

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Update System and Install Apache
        run: |
          sudo apt-get update -y
          sudo apt-get install -y apache2
          sudo systemctl start apache2
          sudo systemctl enable apache2

      - name: Deploy Application Files
        run: |
          sudo cp -r . /var/www/html
          sudo chown -R www-data:www-data /var/www/html
          sudo systemctl restart apache2
